### PR TITLE
Update README instructions to restore current work directory

### PR DESCRIPTION
**Pull request by lxylxy123456**
Add a `cd` command to make sure we are at the right `$PWD`

### CODE REVIEW

**Review by dtomassi — CHANGES_REQUESTED** [review]
What about changing step 5 to `$ cd ..`?

**Comment by lxylxy123456** [comment]
That does not really work because if the user is using a local MongoDB ("Note: If you wish to use your own local MongoDB, skip to Step 4.") they would still be in ~. 

Another problem is that if using a local MongoDB, the user need to run `run.py` manually (not mentioned in README). I am still experimenting and did not have a chance to put it into an issue.

**Comment by dtomassi** [comment]
@lxylxy123456 I see. Do you think it would be simpler for a user if we just made it a requirement to use the docker image for the database?

**Comment by lxylxy123456** [comment]
Yes, I think it will be simpler, since the user should always have Docker in their environment. 

I noticed that some database records are stored in `database/dump` directly and restored using `mongorestore`. Will this possibly corrupt a user's database if not using docker images?

**Comment by aalmanza1998** [comment]
> Yes, I think it will be simpler, since the user should always have Docker in their environment.
> 
> I noticed that some database records are stored in `database/dump` directly and restored using `mongorestore`. Will this possibly corrupt a user's database if not using docker images?

I agree that at least for now we should make it a requirement to use the docker image for the db since there seems to be some steps that are needed but not documented on the the README. 

@lxylxy123456  Could you please elaborate a little more on the concern you brought up with using `mongorestore`?

**Comment by lxylxy123456** [comment]
My concern is that if the user is using their own database, the `mongorestore` operation may add some unwanted data to the user's database (e.g. unexpected administrator accounts). Also, this makes the project less readable because it is difficult to see what is contained in files in `database/dump`. 

It is better to replace the content with MongoDB commands (e.g. `insert into administrators values ...` for some other databases. I am not very sure how it looks like in MongoDB's NoSQL language)

**Comment by aalmanza1998** [comment]
> My concern is that if the user is using their own database, the `mongorestore` operation may add some unwanted data to the user's database (e.g. unexpected administrator accounts). Also, this makes the project less readable because it is difficult to see what is contained in files in `database/dump`.
> 
> It is better to replace the content with MongoDB commands (e.g. `insert into administrators values ...` for some other databases. I am not very sure how it looks like in MongoDB's NoSQL language)

I see what you mean. In any case, do you think making it a requirement to use the docker image for the db would be better/ eliminate this concern? At least until we look into and document all the steps needed to use your own db and the implications it would have?

**Comment by lxylxy123456** [comment]
I think for now requirement for docker image is good. 
For future works, we need to
1. Write instructions for using a local MongoDB
2. Switch `mongorestore` to other ways to construct the database
3. Explain how can the user manage the database (e.g. backup / restore the database; what happens if the container is stopped by accidentally? is it possible to get the data back and start a new container?)

**Comment by dtomassi** [comment]
> I think for now requirement for docker image is good.
> For future works, we need to
> 
> 1. Write instructions for using a local MongoDB
> 2. Switch `mongorestore` to other ways to construct the database
> 3. Explain how can the user manage the database (e.g. backup / restore the database; what happens if the container is stopped by accidentally? is it possible to get the data back and start a new container?)

1. I think we are going to remove the local MongoDB from our instructions and make the Docker version mandatory.
2. I am not sure this will be needed when using the Docker version.
3. A user can start the docker container again and have access to their data. I am not sure if telling people how to do database management is necessary.

**Comment by lxylxy123456** [comment]
2 is actually not necessary. It is a long term enhancement. 
3 I think since people can restart containers (I just realized it), we do not need to mention the database management part.

**Comment by lxylxy123456** [comment]
I think nothing needs to be changed for this PR. I can open other PRs for other orthogonal issues.

**Review by dtomassi — APPROVED** [review]
LGTM

**Pull request merged**
